qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out1 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error1 ./shells/boston/indep/v1.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out2 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error2 ./shells/boston/indep/v2.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out3 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error3 ./shells/boston/indep/v3.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out4 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error4 ./shells/boston/indep/v4.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out5 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error5 ./shells/boston/indep/v5.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out6 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error6 ./shells/boston/indep/v6.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out7 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error7 ./shells/boston/indep/v7.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out8 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error8 ./shells/boston/indep/v8.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out9 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error9 ./shells/boston/indep/v9.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out10 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error10 ./shells/boston/indep/v10.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out11 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error11 ./shells/boston/indep/v11.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out12 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error12 ./shells/boston/indep/v12.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out13 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error13 ./shells/boston/indep/v13.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out14 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error14 ./shells/boston/indep/v14.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out15 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error15 ./shells/boston/indep/v15.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out16 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error16 ./shells/boston/indep/v16.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out17 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error17 ./shells/boston/indep/v17.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out18 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error18 ./shells/boston/indep/v18.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out19 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error19 ./shells/boston/indep/v19.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out20 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error20 ./shells/boston/indep/v20.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out21 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error21 ./shells/boston/indep/v21.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out22 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error22 ./shells/boston/indep/v22.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out23 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error23 ./shells/boston/indep/v23.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out24 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error24 ./shells/boston/indep/v24.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out25 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error25 ./shells/boston/indep/v25.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out26 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error26 ./shells/boston/indep/v26.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out27 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error27 ./shells/boston/indep/v27.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out28 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error28 ./shells/boston/indep/v28.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out29 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error29 ./shells/boston/indep/v29.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out30 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error30 ./shells/boston/indep/v30.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out31 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error31 ./shells/boston/indep/v31.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out32 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error32 ./shells/boston/indep/v32.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out33 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error33 ./shells/boston/indep/v33.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out34 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error34 ./shells/boston/indep/v34.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out35 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error35 ./shells/boston/indep/v35.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out36 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error36 ./shells/boston/indep/v36.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out37 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error37 ./shells/boston/indep/v37.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out38 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error38 ./shells/boston/indep/v38.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out39 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error39 ./shells/boston/indep/v39.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out40 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error40 ./shells/boston/indep/v40.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out41 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error41 ./shells/boston/indep/v41.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out42 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error42 ./shells/boston/indep/v42.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out43 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error43 ./shells/boston/indep/v43.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out44 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error44 ./shells/boston/indep/v44.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out45 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error45 ./shells/boston/indep/v45.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out46 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error46 ./shells/boston/indep/v46.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out47 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error47 ./shells/boston/indep/v47.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out48 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error48 ./shells/boston/indep/v48.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out49 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error49 ./shells/boston/indep/v49.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out50 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error50 ./shells/boston/indep/v50.sh
