qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out1 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error1 ./shells/boston/indep/v1.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out1 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error1 ./shells/boston/correl/v1.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out1 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error1 ./shells/boston/multitask/v1.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out2 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error2 ./shells/boston/indep/v2.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out2 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error2 ./shells/boston/correl/v2.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out2 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error2 ./shells/boston/multitask/v2.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out3 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error3 ./shells/boston/indep/v3.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out3 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error3 ./shells/boston/correl/v3.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out3 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error3 ./shells/boston/multitask/v3.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out4 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error4 ./shells/boston/indep/v4.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out4 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error4 ./shells/boston/correl/v4.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out4 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error4 ./shells/boston/multitask/v4.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out5 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error5 ./shells/boston/indep/v5.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out5 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error5 ./shells/boston/correl/v5.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out5 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error5 ./shells/boston/multitask/v5.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out6 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error6 ./shells/boston/indep/v6.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out6 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error6 ./shells/boston/correl/v6.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out6 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error6 ./shells/boston/multitask/v6.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out7 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error7 ./shells/boston/indep/v7.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out7 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error7 ./shells/boston/correl/v7.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out7 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error7 ./shells/boston/multitask/v7.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out8 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error8 ./shells/boston/indep/v8.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out8 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error8 ./shells/boston/correl/v8.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out8 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error8 ./shells/boston/multitask/v8.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out9 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error9 ./shells/boston/indep/v9.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out9 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error9 ./shells/boston/correl/v9.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out9 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error9 ./shells/boston/multitask/v9.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out10 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error10 ./shells/boston/indep/v10.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out10 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error10 ./shells/boston/correl/v10.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out10 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error10 ./shells/boston/multitask/v10.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out11 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error11 ./shells/boston/indep/v11.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out11 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error11 ./shells/boston/correl/v11.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out11 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error11 ./shells/boston/multitask/v11.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out12 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error12 ./shells/boston/indep/v12.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out12 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error12 ./shells/boston/correl/v12.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out12 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error12 ./shells/boston/multitask/v12.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out13 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error13 ./shells/boston/indep/v13.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out13 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error13 ./shells/boston/correl/v13.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out13 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error13 ./shells/boston/multitask/v13.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out14 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error14 ./shells/boston/indep/v14.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out14 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error14 ./shells/boston/correl/v14.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out14 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error14 ./shells/boston/multitask/v14.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out15 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error15 ./shells/boston/indep/v15.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out15 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error15 ./shells/boston/correl/v15.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out15 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error15 ./shells/boston/multitask/v15.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out16 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error16 ./shells/boston/indep/v16.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out16 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error16 ./shells/boston/correl/v16.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out16 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error16 ./shells/boston/multitask/v16.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out17 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error17 ./shells/boston/indep/v17.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out17 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error17 ./shells/boston/correl/v17.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out17 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error17 ./shells/boston/multitask/v17.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out18 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error18 ./shells/boston/indep/v18.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out18 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error18 ./shells/boston/correl/v18.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out18 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error18 ./shells/boston/multitask/v18.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out19 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error19 ./shells/boston/indep/v19.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out19 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error19 ./shells/boston/correl/v19.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out19 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error19 ./shells/boston/multitask/v19.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out20 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error20 ./shells/boston/indep/v20.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out20 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error20 ./shells/boston/correl/v20.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out20 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error20 ./shells/boston/multitask/v20.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out21 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error21 ./shells/boston/indep/v21.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out21 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error21 ./shells/boston/correl/v21.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out21 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error21 ./shells/boston/multitask/v21.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out22 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error22 ./shells/boston/indep/v22.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out22 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error22 ./shells/boston/correl/v22.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out22 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error22 ./shells/boston/multitask/v22.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out23 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error23 ./shells/boston/indep/v23.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out23 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error23 ./shells/boston/correl/v23.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out23 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error23 ./shells/boston/multitask/v23.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out24 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error24 ./shells/boston/indep/v24.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out24 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error24 ./shells/boston/correl/v24.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out24 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error24 ./shells/boston/multitask/v24.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out25 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error25 ./shells/boston/indep/v25.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out25 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error25 ./shells/boston/correl/v25.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out25 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error25 ./shells/boston/multitask/v25.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out26 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error26 ./shells/boston/indep/v26.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out26 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error26 ./shells/boston/correl/v26.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out26 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error26 ./shells/boston/multitask/v26.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out27 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error27 ./shells/boston/indep/v27.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out27 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error27 ./shells/boston/correl/v27.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out27 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error27 ./shells/boston/multitask/v27.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out28 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error28 ./shells/boston/indep/v28.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out28 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error28 ./shells/boston/correl/v28.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out28 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error28 ./shells/boston/multitask/v28.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out29 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error29 ./shells/boston/indep/v29.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out29 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error29 ./shells/boston/correl/v29.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out29 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error29 ./shells/boston/multitask/v29.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out30 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error30 ./shells/boston/indep/v30.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out30 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error30 ./shells/boston/correl/v30.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out30 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error30 ./shells/boston/multitask/v30.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out31 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error31 ./shells/boston/indep/v31.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out31 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error31 ./shells/boston/correl/v31.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out31 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error31 ./shells/boston/multitask/v31.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out32 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error32 ./shells/boston/indep/v32.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out32 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error32 ./shells/boston/correl/v32.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out32 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error32 ./shells/boston/multitask/v32.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out33 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error33 ./shells/boston/indep/v33.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out33 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error33 ./shells/boston/correl/v33.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out33 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error33 ./shells/boston/multitask/v33.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out34 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error34 ./shells/boston/indep/v34.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out34 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error34 ./shells/boston/correl/v34.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out34 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error34 ./shells/boston/multitask/v34.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out35 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error35 ./shells/boston/indep/v35.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out35 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error35 ./shells/boston/correl/v35.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out35 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error35 ./shells/boston/multitask/v35.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out36 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error36 ./shells/boston/indep/v36.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out36 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error36 ./shells/boston/correl/v36.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out36 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error36 ./shells/boston/multitask/v36.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out37 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error37 ./shells/boston/indep/v37.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out37 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error37 ./shells/boston/correl/v37.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out37 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error37 ./shells/boston/multitask/v37.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out38 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error38 ./shells/boston/indep/v38.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out38 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error38 ./shells/boston/correl/v38.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out38 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error38 ./shells/boston/multitask/v38.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out39 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error39 ./shells/boston/indep/v39.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out39 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error39 ./shells/boston/correl/v39.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out39 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error39 ./shells/boston/multitask/v39.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out40 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error40 ./shells/boston/indep/v40.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out40 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error40 ./shells/boston/correl/v40.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out40 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error40 ./shells/boston/multitask/v40.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out41 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error41 ./shells/boston/indep/v41.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out41 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error41 ./shells/boston/correl/v41.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out41 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error41 ./shells/boston/multitask/v41.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out42 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error42 ./shells/boston/indep/v42.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out42 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error42 ./shells/boston/correl/v42.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out42 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error42 ./shells/boston/multitask/v42.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out43 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error43 ./shells/boston/indep/v43.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out43 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error43 ./shells/boston/correl/v43.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out43 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error43 ./shells/boston/multitask/v43.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out44 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error44 ./shells/boston/indep/v44.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out44 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error44 ./shells/boston/correl/v44.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out44 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error44 ./shells/boston/multitask/v44.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out45 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error45 ./shells/boston/indep/v45.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out45 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error45 ./shells/boston/correl/v45.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out45 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error45 ./shells/boston/multitask/v45.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out46 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error46 ./shells/boston/indep/v46.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out46 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error46 ./shells/boston/correl/v46.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out46 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error46 ./shells/boston/multitask/v46.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out47 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error47 ./shells/boston/indep/v47.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out47 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error47 ./shells/boston/correl/v47.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out47 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error47 ./shells/boston/multitask/v47.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out48 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error48 ./shells/boston/indep/v48.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out48 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error48 ./shells/boston/correl/v48.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out48 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error48 ./shells/boston/multitask/v48.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out49 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error49 ./shells/boston/indep/v49.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out49 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error49 ./shells/boston/correl/v49.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out49 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error49 ./shells/boston/multitask/v49.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/indep/out50 -e /bigscratch/as793/multi_objective_bayesopt/boston/indep/error50 ./shells/boston/indep/v50.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/correl/out50 -e /bigscratch/as793/multi_objective_bayesopt/boston/correl/error50 ./shells/boston/correl/v50.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/boston/multitask/out50 -e /bigscratch/as793/multi_objective_bayesopt/boston/multitask/error50 ./shells/boston/multitask/v50.sh
