qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out1 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error1 ./shells/gp_onequarter/indep/v1.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out1 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error1 ./shells/gp_onequarter/correl/v1.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out1 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error1 ./shells/gp_onequarter/multitask/v1.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out1 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error1 ./shells/gp_onequarter/parego/v1.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out1 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error1 ./shells/gp_onequarter/random/v1.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out2 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error2 ./shells/gp_onequarter/indep/v2.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out2 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error2 ./shells/gp_onequarter/correl/v2.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out2 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error2 ./shells/gp_onequarter/multitask/v2.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out2 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error2 ./shells/gp_onequarter/parego/v2.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out2 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error2 ./shells/gp_onequarter/random/v2.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out3 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error3 ./shells/gp_onequarter/indep/v3.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out3 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error3 ./shells/gp_onequarter/correl/v3.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out3 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error3 ./shells/gp_onequarter/multitask/v3.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out3 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error3 ./shells/gp_onequarter/parego/v3.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out3 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error3 ./shells/gp_onequarter/random/v3.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out4 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error4 ./shells/gp_onequarter/indep/v4.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out4 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error4 ./shells/gp_onequarter/correl/v4.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out4 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error4 ./shells/gp_onequarter/multitask/v4.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out4 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error4 ./shells/gp_onequarter/parego/v4.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out4 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error4 ./shells/gp_onequarter/random/v4.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out5 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error5 ./shells/gp_onequarter/indep/v5.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out5 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error5 ./shells/gp_onequarter/correl/v5.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out5 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error5 ./shells/gp_onequarter/multitask/v5.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out5 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error5 ./shells/gp_onequarter/parego/v5.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out5 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error5 ./shells/gp_onequarter/random/v5.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out6 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error6 ./shells/gp_onequarter/indep/v6.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out6 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error6 ./shells/gp_onequarter/correl/v6.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out6 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error6 ./shells/gp_onequarter/multitask/v6.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out6 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error6 ./shells/gp_onequarter/parego/v6.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out6 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error6 ./shells/gp_onequarter/random/v6.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out7 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error7 ./shells/gp_onequarter/indep/v7.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out7 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error7 ./shells/gp_onequarter/correl/v7.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out7 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error7 ./shells/gp_onequarter/multitask/v7.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out7 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error7 ./shells/gp_onequarter/parego/v7.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out7 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error7 ./shells/gp_onequarter/random/v7.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out8 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error8 ./shells/gp_onequarter/indep/v8.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out8 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error8 ./shells/gp_onequarter/correl/v8.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out8 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error8 ./shells/gp_onequarter/multitask/v8.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out8 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error8 ./shells/gp_onequarter/parego/v8.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out8 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error8 ./shells/gp_onequarter/random/v8.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out9 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error9 ./shells/gp_onequarter/indep/v9.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out9 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error9 ./shells/gp_onequarter/correl/v9.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out9 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error9 ./shells/gp_onequarter/multitask/v9.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out9 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error9 ./shells/gp_onequarter/parego/v9.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out9 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error9 ./shells/gp_onequarter/random/v9.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out10 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error10 ./shells/gp_onequarter/indep/v10.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out10 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error10 ./shells/gp_onequarter/correl/v10.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out10 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error10 ./shells/gp_onequarter/multitask/v10.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out10 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error10 ./shells/gp_onequarter/parego/v10.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out10 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error10 ./shells/gp_onequarter/random/v10.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out11 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error11 ./shells/gp_onequarter/indep/v11.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out11 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error11 ./shells/gp_onequarter/correl/v11.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out11 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error11 ./shells/gp_onequarter/multitask/v11.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out11 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error11 ./shells/gp_onequarter/parego/v11.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out11 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error11 ./shells/gp_onequarter/random/v11.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out12 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error12 ./shells/gp_onequarter/indep/v12.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out12 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error12 ./shells/gp_onequarter/correl/v12.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out12 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error12 ./shells/gp_onequarter/multitask/v12.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out12 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error12 ./shells/gp_onequarter/parego/v12.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out12 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error12 ./shells/gp_onequarter/random/v12.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out13 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error13 ./shells/gp_onequarter/indep/v13.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out13 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error13 ./shells/gp_onequarter/correl/v13.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out13 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error13 ./shells/gp_onequarter/multitask/v13.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out13 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error13 ./shells/gp_onequarter/parego/v13.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out13 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error13 ./shells/gp_onequarter/random/v13.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out14 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error14 ./shells/gp_onequarter/indep/v14.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out14 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error14 ./shells/gp_onequarter/correl/v14.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out14 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error14 ./shells/gp_onequarter/multitask/v14.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out14 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error14 ./shells/gp_onequarter/parego/v14.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out14 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error14 ./shells/gp_onequarter/random/v14.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out15 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error15 ./shells/gp_onequarter/indep/v15.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out15 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error15 ./shells/gp_onequarter/correl/v15.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out15 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error15 ./shells/gp_onequarter/multitask/v15.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out15 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error15 ./shells/gp_onequarter/parego/v15.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out15 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error15 ./shells/gp_onequarter/random/v15.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out16 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error16 ./shells/gp_onequarter/indep/v16.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out16 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error16 ./shells/gp_onequarter/correl/v16.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out16 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error16 ./shells/gp_onequarter/multitask/v16.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out16 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error16 ./shells/gp_onequarter/parego/v16.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out16 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error16 ./shells/gp_onequarter/random/v16.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out17 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error17 ./shells/gp_onequarter/indep/v17.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out17 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error17 ./shells/gp_onequarter/correl/v17.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out17 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error17 ./shells/gp_onequarter/multitask/v17.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out17 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error17 ./shells/gp_onequarter/parego/v17.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out17 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error17 ./shells/gp_onequarter/random/v17.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out18 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error18 ./shells/gp_onequarter/indep/v18.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out18 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error18 ./shells/gp_onequarter/correl/v18.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out18 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error18 ./shells/gp_onequarter/multitask/v18.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out18 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error18 ./shells/gp_onequarter/parego/v18.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out18 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error18 ./shells/gp_onequarter/random/v18.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out19 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error19 ./shells/gp_onequarter/indep/v19.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out19 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error19 ./shells/gp_onequarter/correl/v19.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out19 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error19 ./shells/gp_onequarter/multitask/v19.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out19 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error19 ./shells/gp_onequarter/parego/v19.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out19 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error19 ./shells/gp_onequarter/random/v19.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out20 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error20 ./shells/gp_onequarter/indep/v20.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out20 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error20 ./shells/gp_onequarter/correl/v20.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out20 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error20 ./shells/gp_onequarter/multitask/v20.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out20 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error20 ./shells/gp_onequarter/parego/v20.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out20 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error20 ./shells/gp_onequarter/random/v20.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out21 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error21 ./shells/gp_onequarter/indep/v21.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out21 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error21 ./shells/gp_onequarter/correl/v21.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out21 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error21 ./shells/gp_onequarter/multitask/v21.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out21 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error21 ./shells/gp_onequarter/parego/v21.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out21 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error21 ./shells/gp_onequarter/random/v21.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out22 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error22 ./shells/gp_onequarter/indep/v22.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out22 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error22 ./shells/gp_onequarter/correl/v22.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out22 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error22 ./shells/gp_onequarter/multitask/v22.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out22 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error22 ./shells/gp_onequarter/parego/v22.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out22 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error22 ./shells/gp_onequarter/random/v22.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out23 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error23 ./shells/gp_onequarter/indep/v23.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out23 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error23 ./shells/gp_onequarter/correl/v23.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out23 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error23 ./shells/gp_onequarter/multitask/v23.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out23 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error23 ./shells/gp_onequarter/parego/v23.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out23 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error23 ./shells/gp_onequarter/random/v23.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out24 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error24 ./shells/gp_onequarter/indep/v24.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out24 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error24 ./shells/gp_onequarter/correl/v24.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out24 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error24 ./shells/gp_onequarter/multitask/v24.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out24 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error24 ./shells/gp_onequarter/parego/v24.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out24 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error24 ./shells/gp_onequarter/random/v24.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out25 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error25 ./shells/gp_onequarter/indep/v25.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out25 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error25 ./shells/gp_onequarter/correl/v25.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out25 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error25 ./shells/gp_onequarter/multitask/v25.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out25 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error25 ./shells/gp_onequarter/parego/v25.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out25 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error25 ./shells/gp_onequarter/random/v25.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out26 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error26 ./shells/gp_onequarter/indep/v26.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out26 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error26 ./shells/gp_onequarter/correl/v26.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out26 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error26 ./shells/gp_onequarter/multitask/v26.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out26 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error26 ./shells/gp_onequarter/parego/v26.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out26 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error26 ./shells/gp_onequarter/random/v26.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out27 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error27 ./shells/gp_onequarter/indep/v27.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out27 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error27 ./shells/gp_onequarter/correl/v27.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out27 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error27 ./shells/gp_onequarter/multitask/v27.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out27 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error27 ./shells/gp_onequarter/parego/v27.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out27 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error27 ./shells/gp_onequarter/random/v27.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out28 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error28 ./shells/gp_onequarter/indep/v28.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out28 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error28 ./shells/gp_onequarter/correl/v28.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out28 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error28 ./shells/gp_onequarter/multitask/v28.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out28 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error28 ./shells/gp_onequarter/parego/v28.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out28 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error28 ./shells/gp_onequarter/random/v28.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out29 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error29 ./shells/gp_onequarter/indep/v29.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out29 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error29 ./shells/gp_onequarter/correl/v29.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out29 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error29 ./shells/gp_onequarter/multitask/v29.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out29 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error29 ./shells/gp_onequarter/parego/v29.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out29 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error29 ./shells/gp_onequarter/random/v29.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out30 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error30 ./shells/gp_onequarter/indep/v30.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out30 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error30 ./shells/gp_onequarter/correl/v30.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out30 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error30 ./shells/gp_onequarter/multitask/v30.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out30 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error30 ./shells/gp_onequarter/parego/v30.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out30 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error30 ./shells/gp_onequarter/random/v30.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out31 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error31 ./shells/gp_onequarter/indep/v31.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out31 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error31 ./shells/gp_onequarter/correl/v31.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out31 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error31 ./shells/gp_onequarter/multitask/v31.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out31 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error31 ./shells/gp_onequarter/parego/v31.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out31 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error31 ./shells/gp_onequarter/random/v31.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out32 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error32 ./shells/gp_onequarter/indep/v32.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out32 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error32 ./shells/gp_onequarter/correl/v32.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out32 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error32 ./shells/gp_onequarter/multitask/v32.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out32 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error32 ./shells/gp_onequarter/parego/v32.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out32 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error32 ./shells/gp_onequarter/random/v32.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out33 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error33 ./shells/gp_onequarter/indep/v33.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out33 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error33 ./shells/gp_onequarter/correl/v33.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out33 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error33 ./shells/gp_onequarter/multitask/v33.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out33 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error33 ./shells/gp_onequarter/parego/v33.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out33 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error33 ./shells/gp_onequarter/random/v33.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out34 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error34 ./shells/gp_onequarter/indep/v34.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out34 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error34 ./shells/gp_onequarter/correl/v34.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out34 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error34 ./shells/gp_onequarter/multitask/v34.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out34 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error34 ./shells/gp_onequarter/parego/v34.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out34 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error34 ./shells/gp_onequarter/random/v34.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out35 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error35 ./shells/gp_onequarter/indep/v35.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out35 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error35 ./shells/gp_onequarter/correl/v35.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out35 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error35 ./shells/gp_onequarter/multitask/v35.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out35 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error35 ./shells/gp_onequarter/parego/v35.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out35 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error35 ./shells/gp_onequarter/random/v35.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out36 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error36 ./shells/gp_onequarter/indep/v36.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out36 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error36 ./shells/gp_onequarter/correl/v36.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out36 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error36 ./shells/gp_onequarter/multitask/v36.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out36 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error36 ./shells/gp_onequarter/parego/v36.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out36 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error36 ./shells/gp_onequarter/random/v36.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out37 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error37 ./shells/gp_onequarter/indep/v37.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out37 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error37 ./shells/gp_onequarter/correl/v37.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out37 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error37 ./shells/gp_onequarter/multitask/v37.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out37 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error37 ./shells/gp_onequarter/parego/v37.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out37 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error37 ./shells/gp_onequarter/random/v37.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out38 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error38 ./shells/gp_onequarter/indep/v38.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out38 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error38 ./shells/gp_onequarter/correl/v38.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out38 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error38 ./shells/gp_onequarter/multitask/v38.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out38 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error38 ./shells/gp_onequarter/parego/v38.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out38 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error38 ./shells/gp_onequarter/random/v38.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out39 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error39 ./shells/gp_onequarter/indep/v39.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out39 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error39 ./shells/gp_onequarter/correl/v39.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out39 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error39 ./shells/gp_onequarter/multitask/v39.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out39 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error39 ./shells/gp_onequarter/parego/v39.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out39 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error39 ./shells/gp_onequarter/random/v39.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out40 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error40 ./shells/gp_onequarter/indep/v40.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out40 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error40 ./shells/gp_onequarter/correl/v40.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out40 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error40 ./shells/gp_onequarter/multitask/v40.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out40 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error40 ./shells/gp_onequarter/parego/v40.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out40 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error40 ./shells/gp_onequarter/random/v40.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out41 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error41 ./shells/gp_onequarter/indep/v41.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out41 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error41 ./shells/gp_onequarter/correl/v41.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out41 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error41 ./shells/gp_onequarter/multitask/v41.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out41 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error41 ./shells/gp_onequarter/parego/v41.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out41 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error41 ./shells/gp_onequarter/random/v41.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out42 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error42 ./shells/gp_onequarter/indep/v42.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out42 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error42 ./shells/gp_onequarter/correl/v42.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out42 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error42 ./shells/gp_onequarter/multitask/v42.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out42 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error42 ./shells/gp_onequarter/parego/v42.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out42 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error42 ./shells/gp_onequarter/random/v42.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out43 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error43 ./shells/gp_onequarter/indep/v43.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out43 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error43 ./shells/gp_onequarter/correl/v43.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out43 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error43 ./shells/gp_onequarter/multitask/v43.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out43 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error43 ./shells/gp_onequarter/parego/v43.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out43 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error43 ./shells/gp_onequarter/random/v43.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out44 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error44 ./shells/gp_onequarter/indep/v44.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out44 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error44 ./shells/gp_onequarter/correl/v44.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out44 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error44 ./shells/gp_onequarter/multitask/v44.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out44 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error44 ./shells/gp_onequarter/parego/v44.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out44 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error44 ./shells/gp_onequarter/random/v44.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out45 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error45 ./shells/gp_onequarter/indep/v45.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out45 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error45 ./shells/gp_onequarter/correl/v45.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out45 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error45 ./shells/gp_onequarter/multitask/v45.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out45 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error45 ./shells/gp_onequarter/parego/v45.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out45 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error45 ./shells/gp_onequarter/random/v45.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out46 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error46 ./shells/gp_onequarter/indep/v46.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out46 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error46 ./shells/gp_onequarter/correl/v46.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out46 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error46 ./shells/gp_onequarter/multitask/v46.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out46 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error46 ./shells/gp_onequarter/parego/v46.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out46 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error46 ./shells/gp_onequarter/random/v46.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out47 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error47 ./shells/gp_onequarter/indep/v47.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out47 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error47 ./shells/gp_onequarter/correl/v47.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out47 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error47 ./shells/gp_onequarter/multitask/v47.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out47 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error47 ./shells/gp_onequarter/parego/v47.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out47 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error47 ./shells/gp_onequarter/random/v47.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out48 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error48 ./shells/gp_onequarter/indep/v48.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out48 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error48 ./shells/gp_onequarter/correl/v48.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out48 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error48 ./shells/gp_onequarter/multitask/v48.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out48 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error48 ./shells/gp_onequarter/parego/v48.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out48 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error48 ./shells/gp_onequarter/random/v48.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out49 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error49 ./shells/gp_onequarter/indep/v49.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out49 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error49 ./shells/gp_onequarter/correl/v49.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out49 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error49 ./shells/gp_onequarter/multitask/v49.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out49 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error49 ./shells/gp_onequarter/parego/v49.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out49 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error49 ./shells/gp_onequarter/random/v49.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/out50 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/indep/error50 ./shells/gp_onequarter/indep/v50.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/out50 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/correl/error50 ./shells/gp_onequarter/correl/v50.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/out50 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/multitask/error50 ./shells/gp_onequarter/multitask/v50.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/out50 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/parego/error50 ./shells/gp_onequarter/parego/v50.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/out50 -e /bigscratch/as793/multi_objective_bayesopt/gp_onequarter/random/error50 ./shells/gp_onequarter/random/v50.sh
