qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out1 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error1 ./shells/gp_threequarters/indep/1.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out1 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error1 ./shells/gp_threequarters/correl/1.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out1 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error1 ./shells/gp_threequarters/multitask/1.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out1 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error1 ./shells/gp_threequarters/parego/1.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out1 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error1 ./shells/gp_threequarters/random/1.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out2 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error2 ./shells/gp_threequarters/indep/2.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out2 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error2 ./shells/gp_threequarters/correl/2.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out2 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error2 ./shells/gp_threequarters/multitask/2.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out2 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error2 ./shells/gp_threequarters/parego/2.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out2 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error2 ./shells/gp_threequarters/random/2.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out3 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error3 ./shells/gp_threequarters/indep/3.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out3 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error3 ./shells/gp_threequarters/correl/3.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out3 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error3 ./shells/gp_threequarters/multitask/3.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out3 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error3 ./shells/gp_threequarters/parego/3.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out3 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error3 ./shells/gp_threequarters/random/3.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out4 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error4 ./shells/gp_threequarters/indep/4.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out4 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error4 ./shells/gp_threequarters/correl/4.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out4 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error4 ./shells/gp_threequarters/multitask/4.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out4 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error4 ./shells/gp_threequarters/parego/4.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out4 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error4 ./shells/gp_threequarters/random/4.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out5 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error5 ./shells/gp_threequarters/indep/5.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out5 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error5 ./shells/gp_threequarters/correl/5.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out5 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error5 ./shells/gp_threequarters/multitask/5.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out5 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error5 ./shells/gp_threequarters/parego/5.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out5 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error5 ./shells/gp_threequarters/random/5.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out6 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error6 ./shells/gp_threequarters/indep/6.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out6 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error6 ./shells/gp_threequarters/correl/6.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out6 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error6 ./shells/gp_threequarters/multitask/6.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out6 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error6 ./shells/gp_threequarters/parego/6.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out6 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error6 ./shells/gp_threequarters/random/6.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out7 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error7 ./shells/gp_threequarters/indep/7.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out7 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error7 ./shells/gp_threequarters/correl/7.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out7 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error7 ./shells/gp_threequarters/multitask/7.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out7 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error7 ./shells/gp_threequarters/parego/7.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out7 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error7 ./shells/gp_threequarters/random/7.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out8 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error8 ./shells/gp_threequarters/indep/8.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out8 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error8 ./shells/gp_threequarters/correl/8.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out8 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error8 ./shells/gp_threequarters/multitask/8.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out8 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error8 ./shells/gp_threequarters/parego/8.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out8 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error8 ./shells/gp_threequarters/random/8.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out9 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error9 ./shells/gp_threequarters/indep/9.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out9 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error9 ./shells/gp_threequarters/correl/9.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out9 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error9 ./shells/gp_threequarters/multitask/9.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out9 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error9 ./shells/gp_threequarters/parego/9.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out9 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error9 ./shells/gp_threequarters/random/9.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out10 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error10 ./shells/gp_threequarters/indep/10.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out10 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error10 ./shells/gp_threequarters/correl/10.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out10 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error10 ./shells/gp_threequarters/multitask/10.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out10 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error10 ./shells/gp_threequarters/parego/10.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out10 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error10 ./shells/gp_threequarters/random/10.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out11 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error11 ./shells/gp_threequarters/indep/11.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out11 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error11 ./shells/gp_threequarters/correl/11.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out11 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error11 ./shells/gp_threequarters/multitask/11.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out11 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error11 ./shells/gp_threequarters/parego/11.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out11 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error11 ./shells/gp_threequarters/random/11.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out12 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error12 ./shells/gp_threequarters/indep/12.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out12 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error12 ./shells/gp_threequarters/correl/12.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out12 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error12 ./shells/gp_threequarters/multitask/12.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out12 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error12 ./shells/gp_threequarters/parego/12.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out12 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error12 ./shells/gp_threequarters/random/12.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out13 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error13 ./shells/gp_threequarters/indep/13.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out13 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error13 ./shells/gp_threequarters/correl/13.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out13 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error13 ./shells/gp_threequarters/multitask/13.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out13 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error13 ./shells/gp_threequarters/parego/13.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out13 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error13 ./shells/gp_threequarters/random/13.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out14 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error14 ./shells/gp_threequarters/indep/14.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out14 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error14 ./shells/gp_threequarters/correl/14.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out14 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error14 ./shells/gp_threequarters/multitask/14.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out14 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error14 ./shells/gp_threequarters/parego/14.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out14 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error14 ./shells/gp_threequarters/random/14.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out15 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error15 ./shells/gp_threequarters/indep/15.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out15 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error15 ./shells/gp_threequarters/correl/15.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out15 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error15 ./shells/gp_threequarters/multitask/15.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out15 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error15 ./shells/gp_threequarters/parego/15.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out15 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error15 ./shells/gp_threequarters/random/15.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out16 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error16 ./shells/gp_threequarters/indep/16.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out16 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error16 ./shells/gp_threequarters/correl/16.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out16 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error16 ./shells/gp_threequarters/multitask/16.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out16 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error16 ./shells/gp_threequarters/parego/16.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out16 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error16 ./shells/gp_threequarters/random/16.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out17 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error17 ./shells/gp_threequarters/indep/17.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out17 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error17 ./shells/gp_threequarters/correl/17.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out17 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error17 ./shells/gp_threequarters/multitask/17.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out17 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error17 ./shells/gp_threequarters/parego/17.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out17 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error17 ./shells/gp_threequarters/random/17.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out18 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error18 ./shells/gp_threequarters/indep/18.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out18 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error18 ./shells/gp_threequarters/correl/18.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out18 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error18 ./shells/gp_threequarters/multitask/18.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out18 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error18 ./shells/gp_threequarters/parego/18.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out18 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error18 ./shells/gp_threequarters/random/18.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out19 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error19 ./shells/gp_threequarters/indep/19.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out19 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error19 ./shells/gp_threequarters/correl/19.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out19 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error19 ./shells/gp_threequarters/multitask/19.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out19 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error19 ./shells/gp_threequarters/parego/19.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out19 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error19 ./shells/gp_threequarters/random/19.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out20 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error20 ./shells/gp_threequarters/indep/20.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out20 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error20 ./shells/gp_threequarters/correl/20.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out20 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error20 ./shells/gp_threequarters/multitask/20.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out20 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error20 ./shells/gp_threequarters/parego/20.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out20 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error20 ./shells/gp_threequarters/random/20.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out21 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error21 ./shells/gp_threequarters/indep/21.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out21 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error21 ./shells/gp_threequarters/correl/21.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out21 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error21 ./shells/gp_threequarters/multitask/21.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out21 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error21 ./shells/gp_threequarters/parego/21.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out21 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error21 ./shells/gp_threequarters/random/21.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out22 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error22 ./shells/gp_threequarters/indep/22.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out22 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error22 ./shells/gp_threequarters/correl/22.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out22 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error22 ./shells/gp_threequarters/multitask/22.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out22 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error22 ./shells/gp_threequarters/parego/22.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out22 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error22 ./shells/gp_threequarters/random/22.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out23 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error23 ./shells/gp_threequarters/indep/23.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out23 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error23 ./shells/gp_threequarters/correl/23.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out23 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error23 ./shells/gp_threequarters/multitask/23.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out23 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error23 ./shells/gp_threequarters/parego/23.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out23 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error23 ./shells/gp_threequarters/random/23.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out24 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error24 ./shells/gp_threequarters/indep/24.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out24 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error24 ./shells/gp_threequarters/correl/24.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out24 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error24 ./shells/gp_threequarters/multitask/24.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out24 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error24 ./shells/gp_threequarters/parego/24.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out24 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error24 ./shells/gp_threequarters/random/24.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out25 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error25 ./shells/gp_threequarters/indep/25.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out25 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error25 ./shells/gp_threequarters/correl/25.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out25 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error25 ./shells/gp_threequarters/multitask/25.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out25 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error25 ./shells/gp_threequarters/parego/25.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out25 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error25 ./shells/gp_threequarters/random/25.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out26 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error26 ./shells/gp_threequarters/indep/26.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out26 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error26 ./shells/gp_threequarters/correl/26.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out26 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error26 ./shells/gp_threequarters/multitask/26.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out26 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error26 ./shells/gp_threequarters/parego/26.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out26 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error26 ./shells/gp_threequarters/random/26.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out27 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error27 ./shells/gp_threequarters/indep/27.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out27 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error27 ./shells/gp_threequarters/correl/27.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out27 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error27 ./shells/gp_threequarters/multitask/27.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out27 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error27 ./shells/gp_threequarters/parego/27.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out27 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error27 ./shells/gp_threequarters/random/27.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out28 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error28 ./shells/gp_threequarters/indep/28.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out28 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error28 ./shells/gp_threequarters/correl/28.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out28 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error28 ./shells/gp_threequarters/multitask/28.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out28 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error28 ./shells/gp_threequarters/parego/28.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out28 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error28 ./shells/gp_threequarters/random/28.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out29 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error29 ./shells/gp_threequarters/indep/29.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out29 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error29 ./shells/gp_threequarters/correl/29.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out29 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error29 ./shells/gp_threequarters/multitask/29.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out29 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error29 ./shells/gp_threequarters/parego/29.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out29 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error29 ./shells/gp_threequarters/random/29.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out30 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error30 ./shells/gp_threequarters/indep/30.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out30 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error30 ./shells/gp_threequarters/correl/30.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out30 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error30 ./shells/gp_threequarters/multitask/30.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out30 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error30 ./shells/gp_threequarters/parego/30.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out30 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error30 ./shells/gp_threequarters/random/30.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out31 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error31 ./shells/gp_threequarters/indep/31.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out31 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error31 ./shells/gp_threequarters/correl/31.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out31 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error31 ./shells/gp_threequarters/multitask/31.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out31 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error31 ./shells/gp_threequarters/parego/31.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out31 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error31 ./shells/gp_threequarters/random/31.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out32 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error32 ./shells/gp_threequarters/indep/32.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out32 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error32 ./shells/gp_threequarters/correl/32.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out32 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error32 ./shells/gp_threequarters/multitask/32.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out32 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error32 ./shells/gp_threequarters/parego/32.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out32 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error32 ./shells/gp_threequarters/random/32.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out33 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error33 ./shells/gp_threequarters/indep/33.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out33 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error33 ./shells/gp_threequarters/correl/33.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out33 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error33 ./shells/gp_threequarters/multitask/33.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out33 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error33 ./shells/gp_threequarters/parego/33.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out33 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error33 ./shells/gp_threequarters/random/33.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out34 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error34 ./shells/gp_threequarters/indep/34.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out34 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error34 ./shells/gp_threequarters/correl/34.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out34 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error34 ./shells/gp_threequarters/multitask/34.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out34 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error34 ./shells/gp_threequarters/parego/34.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out34 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error34 ./shells/gp_threequarters/random/34.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out35 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error35 ./shells/gp_threequarters/indep/35.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out35 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error35 ./shells/gp_threequarters/correl/35.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out35 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error35 ./shells/gp_threequarters/multitask/35.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out35 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error35 ./shells/gp_threequarters/parego/35.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out35 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error35 ./shells/gp_threequarters/random/35.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out36 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error36 ./shells/gp_threequarters/indep/36.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out36 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error36 ./shells/gp_threequarters/correl/36.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out36 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error36 ./shells/gp_threequarters/multitask/36.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out36 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error36 ./shells/gp_threequarters/parego/36.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out36 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error36 ./shells/gp_threequarters/random/36.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out37 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error37 ./shells/gp_threequarters/indep/37.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out37 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error37 ./shells/gp_threequarters/correl/37.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out37 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error37 ./shells/gp_threequarters/multitask/37.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out37 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error37 ./shells/gp_threequarters/parego/37.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out37 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error37 ./shells/gp_threequarters/random/37.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out38 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error38 ./shells/gp_threequarters/indep/38.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out38 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error38 ./shells/gp_threequarters/correl/38.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out38 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error38 ./shells/gp_threequarters/multitask/38.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out38 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error38 ./shells/gp_threequarters/parego/38.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out38 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error38 ./shells/gp_threequarters/random/38.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out39 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error39 ./shells/gp_threequarters/indep/39.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out39 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error39 ./shells/gp_threequarters/correl/39.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out39 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error39 ./shells/gp_threequarters/multitask/39.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out39 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error39 ./shells/gp_threequarters/parego/39.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out39 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error39 ./shells/gp_threequarters/random/39.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out40 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error40 ./shells/gp_threequarters/indep/40.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out40 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error40 ./shells/gp_threequarters/correl/40.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out40 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error40 ./shells/gp_threequarters/multitask/40.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out40 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error40 ./shells/gp_threequarters/parego/40.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out40 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error40 ./shells/gp_threequarters/random/40.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out41 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error41 ./shells/gp_threequarters/indep/41.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out41 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error41 ./shells/gp_threequarters/correl/41.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out41 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error41 ./shells/gp_threequarters/multitask/41.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out41 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error41 ./shells/gp_threequarters/parego/41.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out41 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error41 ./shells/gp_threequarters/random/41.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out42 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error42 ./shells/gp_threequarters/indep/42.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out42 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error42 ./shells/gp_threequarters/correl/42.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out42 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error42 ./shells/gp_threequarters/multitask/42.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out42 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error42 ./shells/gp_threequarters/parego/42.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out42 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error42 ./shells/gp_threequarters/random/42.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out43 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error43 ./shells/gp_threequarters/indep/43.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out43 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error43 ./shells/gp_threequarters/correl/43.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out43 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error43 ./shells/gp_threequarters/multitask/43.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out43 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error43 ./shells/gp_threequarters/parego/43.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out43 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error43 ./shells/gp_threequarters/random/43.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out44 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error44 ./shells/gp_threequarters/indep/44.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out44 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error44 ./shells/gp_threequarters/correl/44.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out44 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error44 ./shells/gp_threequarters/multitask/44.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out44 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error44 ./shells/gp_threequarters/parego/44.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out44 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error44 ./shells/gp_threequarters/random/44.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out45 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error45 ./shells/gp_threequarters/indep/45.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out45 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error45 ./shells/gp_threequarters/correl/45.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out45 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error45 ./shells/gp_threequarters/multitask/45.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out45 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error45 ./shells/gp_threequarters/parego/45.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out45 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error45 ./shells/gp_threequarters/random/45.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out46 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error46 ./shells/gp_threequarters/indep/46.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out46 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error46 ./shells/gp_threequarters/correl/46.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out46 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error46 ./shells/gp_threequarters/multitask/46.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out46 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error46 ./shells/gp_threequarters/parego/46.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out46 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error46 ./shells/gp_threequarters/random/46.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out47 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error47 ./shells/gp_threequarters/indep/47.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out47 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error47 ./shells/gp_threequarters/correl/47.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out47 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error47 ./shells/gp_threequarters/multitask/47.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out47 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error47 ./shells/gp_threequarters/parego/47.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out47 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error47 ./shells/gp_threequarters/random/47.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out48 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error48 ./shells/gp_threequarters/indep/48.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out48 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error48 ./shells/gp_threequarters/correl/48.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out48 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error48 ./shells/gp_threequarters/multitask/48.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out48 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error48 ./shells/gp_threequarters/parego/48.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out48 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error48 ./shells/gp_threequarters/random/48.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out49 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error49 ./shells/gp_threequarters/indep/49.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out49 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error49 ./shells/gp_threequarters/correl/49.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out49 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error49 ./shells/gp_threequarters/multitask/49.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out49 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error49 ./shells/gp_threequarters/parego/49.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out49 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error49 ./shells/gp_threequarters/random/49.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/out50 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/indep/error50 ./shells/gp_threequarters/indep/50.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/out50 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/correl/error50 ./shells/gp_threequarters/correl/50.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/out50 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/multitask/error50 ./shells/gp_threequarters/multitask/50.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/out50 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/parego/error50 ./shells/gp_threequarters/parego/50.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/out50 -e /bigscratch/as793/multi_objective_bayesopt/gp_threequarters/random/error50 ./shells/gp_threequarters/random/50.sh
