qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out1 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error1 ./shells/gp_zero/parego/v1.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out2 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error2 ./shells/gp_zero/parego/v2.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out3 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error3 ./shells/gp_zero/parego/v3.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out4 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error4 ./shells/gp_zero/parego/v4.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out5 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error5 ./shells/gp_zero/parego/v5.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out6 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error6 ./shells/gp_zero/parego/v6.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out7 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error7 ./shells/gp_zero/parego/v7.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out8 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error8 ./shells/gp_zero/parego/v8.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out9 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error9 ./shells/gp_zero/parego/v9.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out10 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error10 ./shells/gp_zero/parego/v10.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out11 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error11 ./shells/gp_zero/parego/v11.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out12 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error12 ./shells/gp_zero/parego/v12.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out13 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error13 ./shells/gp_zero/parego/v13.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out14 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error14 ./shells/gp_zero/parego/v14.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out15 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error15 ./shells/gp_zero/parego/v15.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out16 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error16 ./shells/gp_zero/parego/v16.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out17 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error17 ./shells/gp_zero/parego/v17.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out18 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error18 ./shells/gp_zero/parego/v18.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out19 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error19 ./shells/gp_zero/parego/v19.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out20 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error20 ./shells/gp_zero/parego/v20.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out21 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error21 ./shells/gp_zero/parego/v21.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out22 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error22 ./shells/gp_zero/parego/v22.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out23 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error23 ./shells/gp_zero/parego/v23.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out24 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error24 ./shells/gp_zero/parego/v24.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out25 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error25 ./shells/gp_zero/parego/v25.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out26 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error26 ./shells/gp_zero/parego/v26.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out27 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error27 ./shells/gp_zero/parego/v27.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out28 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error28 ./shells/gp_zero/parego/v28.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out29 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error29 ./shells/gp_zero/parego/v29.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out30 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error30 ./shells/gp_zero/parego/v30.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out31 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error31 ./shells/gp_zero/parego/v31.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out32 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error32 ./shells/gp_zero/parego/v32.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out33 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error33 ./shells/gp_zero/parego/v33.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out34 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error34 ./shells/gp_zero/parego/v34.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out35 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error35 ./shells/gp_zero/parego/v35.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out36 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error36 ./shells/gp_zero/parego/v36.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out37 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error37 ./shells/gp_zero/parego/v37.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out38 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error38 ./shells/gp_zero/parego/v38.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out39 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error39 ./shells/gp_zero/parego/v39.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out40 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error40 ./shells/gp_zero/parego/v40.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out41 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error41 ./shells/gp_zero/parego/v41.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out42 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error42 ./shells/gp_zero/parego/v42.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out43 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error43 ./shells/gp_zero/parego/v43.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out44 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error44 ./shells/gp_zero/parego/v44.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out45 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error45 ./shells/gp_zero/parego/v45.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out46 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error46 ./shells/gp_zero/parego/v46.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out47 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error47 ./shells/gp_zero/parego/v47.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out48 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error48 ./shells/gp_zero/parego/v48.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out49 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error49 ./shells/gp_zero/parego/v49.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/out50 -e /bigscratch/as793/multi_objective_bayesopt/gp_zero/parego/error50 ./shells/gp_zero/parego/v50.sh
