qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out1 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error1 ./shells/oka2/indep/1.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out1 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error1 ./shells/oka2/correl/1.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out1 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error1 ./shells/oka2/multitask/1.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out1 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error1 ./shells/oka2/parego/1.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out1 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error1 ./shells/oka2/random/1.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out2 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error2 ./shells/oka2/indep/2.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out2 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error2 ./shells/oka2/correl/2.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out2 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error2 ./shells/oka2/multitask/2.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out2 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error2 ./shells/oka2/parego/2.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out2 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error2 ./shells/oka2/random/2.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out3 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error3 ./shells/oka2/indep/3.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out3 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error3 ./shells/oka2/correl/3.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out3 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error3 ./shells/oka2/multitask/3.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out3 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error3 ./shells/oka2/parego/3.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out3 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error3 ./shells/oka2/random/3.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out4 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error4 ./shells/oka2/indep/4.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out4 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error4 ./shells/oka2/correl/4.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out4 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error4 ./shells/oka2/multitask/4.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out4 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error4 ./shells/oka2/parego/4.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out4 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error4 ./shells/oka2/random/4.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out5 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error5 ./shells/oka2/indep/5.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out5 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error5 ./shells/oka2/correl/5.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out5 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error5 ./shells/oka2/multitask/5.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out5 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error5 ./shells/oka2/parego/5.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out5 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error5 ./shells/oka2/random/5.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out6 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error6 ./shells/oka2/indep/6.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out6 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error6 ./shells/oka2/correl/6.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out6 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error6 ./shells/oka2/multitask/6.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out6 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error6 ./shells/oka2/parego/6.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out6 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error6 ./shells/oka2/random/6.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out7 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error7 ./shells/oka2/indep/7.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out7 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error7 ./shells/oka2/correl/7.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out7 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error7 ./shells/oka2/multitask/7.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out7 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error7 ./shells/oka2/parego/7.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out7 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error7 ./shells/oka2/random/7.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out8 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error8 ./shells/oka2/indep/8.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out8 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error8 ./shells/oka2/correl/8.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out8 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error8 ./shells/oka2/multitask/8.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out8 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error8 ./shells/oka2/parego/8.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out8 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error8 ./shells/oka2/random/8.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out9 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error9 ./shells/oka2/indep/9.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out9 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error9 ./shells/oka2/correl/9.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out9 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error9 ./shells/oka2/multitask/9.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out9 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error9 ./shells/oka2/parego/9.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out9 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error9 ./shells/oka2/random/9.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out10 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error10 ./shells/oka2/indep/10.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out10 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error10 ./shells/oka2/correl/10.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out10 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error10 ./shells/oka2/multitask/10.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out10 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error10 ./shells/oka2/parego/10.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out10 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error10 ./shells/oka2/random/10.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out11 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error11 ./shells/oka2/indep/11.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out11 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error11 ./shells/oka2/correl/11.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out11 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error11 ./shells/oka2/multitask/11.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out11 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error11 ./shells/oka2/parego/11.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out11 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error11 ./shells/oka2/random/11.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out12 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error12 ./shells/oka2/indep/12.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out12 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error12 ./shells/oka2/correl/12.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out12 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error12 ./shells/oka2/multitask/12.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out12 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error12 ./shells/oka2/parego/12.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out12 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error12 ./shells/oka2/random/12.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out13 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error13 ./shells/oka2/indep/13.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out13 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error13 ./shells/oka2/correl/13.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out13 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error13 ./shells/oka2/multitask/13.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out13 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error13 ./shells/oka2/parego/13.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out13 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error13 ./shells/oka2/random/13.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out14 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error14 ./shells/oka2/indep/14.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out14 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error14 ./shells/oka2/correl/14.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out14 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error14 ./shells/oka2/multitask/14.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out14 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error14 ./shells/oka2/parego/14.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out14 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error14 ./shells/oka2/random/14.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out15 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error15 ./shells/oka2/indep/15.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out15 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error15 ./shells/oka2/correl/15.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out15 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error15 ./shells/oka2/multitask/15.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out15 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error15 ./shells/oka2/parego/15.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out15 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error15 ./shells/oka2/random/15.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out16 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error16 ./shells/oka2/indep/16.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out16 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error16 ./shells/oka2/correl/16.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out16 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error16 ./shells/oka2/multitask/16.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out16 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error16 ./shells/oka2/parego/16.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out16 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error16 ./shells/oka2/random/16.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out17 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error17 ./shells/oka2/indep/17.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out17 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error17 ./shells/oka2/correl/17.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out17 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error17 ./shells/oka2/multitask/17.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out17 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error17 ./shells/oka2/parego/17.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out17 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error17 ./shells/oka2/random/17.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out18 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error18 ./shells/oka2/indep/18.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out18 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error18 ./shells/oka2/correl/18.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out18 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error18 ./shells/oka2/multitask/18.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out18 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error18 ./shells/oka2/parego/18.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out18 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error18 ./shells/oka2/random/18.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out19 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error19 ./shells/oka2/indep/19.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out19 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error19 ./shells/oka2/correl/19.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out19 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error19 ./shells/oka2/multitask/19.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out19 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error19 ./shells/oka2/parego/19.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out19 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error19 ./shells/oka2/random/19.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out20 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error20 ./shells/oka2/indep/20.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out20 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error20 ./shells/oka2/correl/20.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out20 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error20 ./shells/oka2/multitask/20.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out20 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error20 ./shells/oka2/parego/20.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out20 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error20 ./shells/oka2/random/20.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out21 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error21 ./shells/oka2/indep/21.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out21 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error21 ./shells/oka2/correl/21.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out21 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error21 ./shells/oka2/multitask/21.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out21 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error21 ./shells/oka2/parego/21.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out21 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error21 ./shells/oka2/random/21.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out22 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error22 ./shells/oka2/indep/22.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out22 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error22 ./shells/oka2/correl/22.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out22 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error22 ./shells/oka2/multitask/22.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out22 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error22 ./shells/oka2/parego/22.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out22 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error22 ./shells/oka2/random/22.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out23 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error23 ./shells/oka2/indep/23.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out23 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error23 ./shells/oka2/correl/23.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out23 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error23 ./shells/oka2/multitask/23.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out23 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error23 ./shells/oka2/parego/23.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out23 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error23 ./shells/oka2/random/23.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out24 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error24 ./shells/oka2/indep/24.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out24 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error24 ./shells/oka2/correl/24.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out24 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error24 ./shells/oka2/multitask/24.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out24 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error24 ./shells/oka2/parego/24.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out24 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error24 ./shells/oka2/random/24.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out25 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error25 ./shells/oka2/indep/25.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out25 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error25 ./shells/oka2/correl/25.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out25 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error25 ./shells/oka2/multitask/25.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out25 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error25 ./shells/oka2/parego/25.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out25 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error25 ./shells/oka2/random/25.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out26 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error26 ./shells/oka2/indep/26.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out26 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error26 ./shells/oka2/correl/26.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out26 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error26 ./shells/oka2/multitask/26.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out26 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error26 ./shells/oka2/parego/26.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out26 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error26 ./shells/oka2/random/26.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out27 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error27 ./shells/oka2/indep/27.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out27 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error27 ./shells/oka2/correl/27.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out27 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error27 ./shells/oka2/multitask/27.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out27 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error27 ./shells/oka2/parego/27.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out27 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error27 ./shells/oka2/random/27.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out28 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error28 ./shells/oka2/indep/28.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out28 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error28 ./shells/oka2/correl/28.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out28 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error28 ./shells/oka2/multitask/28.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out28 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error28 ./shells/oka2/parego/28.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out28 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error28 ./shells/oka2/random/28.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out29 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error29 ./shells/oka2/indep/29.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out29 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error29 ./shells/oka2/correl/29.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out29 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error29 ./shells/oka2/multitask/29.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out29 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error29 ./shells/oka2/parego/29.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out29 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error29 ./shells/oka2/random/29.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out30 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error30 ./shells/oka2/indep/30.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out30 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error30 ./shells/oka2/correl/30.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out30 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error30 ./shells/oka2/multitask/30.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out30 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error30 ./shells/oka2/parego/30.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out30 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error30 ./shells/oka2/random/30.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out31 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error31 ./shells/oka2/indep/31.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out31 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error31 ./shells/oka2/correl/31.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out31 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error31 ./shells/oka2/multitask/31.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out31 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error31 ./shells/oka2/parego/31.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out31 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error31 ./shells/oka2/random/31.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out32 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error32 ./shells/oka2/indep/32.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out32 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error32 ./shells/oka2/correl/32.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out32 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error32 ./shells/oka2/multitask/32.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out32 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error32 ./shells/oka2/parego/32.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out32 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error32 ./shells/oka2/random/32.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out33 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error33 ./shells/oka2/indep/33.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out33 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error33 ./shells/oka2/correl/33.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out33 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error33 ./shells/oka2/multitask/33.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out33 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error33 ./shells/oka2/parego/33.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out33 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error33 ./shells/oka2/random/33.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out34 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error34 ./shells/oka2/indep/34.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out34 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error34 ./shells/oka2/correl/34.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out34 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error34 ./shells/oka2/multitask/34.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out34 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error34 ./shells/oka2/parego/34.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out34 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error34 ./shells/oka2/random/34.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out35 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error35 ./shells/oka2/indep/35.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out35 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error35 ./shells/oka2/correl/35.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out35 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error35 ./shells/oka2/multitask/35.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out35 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error35 ./shells/oka2/parego/35.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out35 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error35 ./shells/oka2/random/35.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out36 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error36 ./shells/oka2/indep/36.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out36 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error36 ./shells/oka2/correl/36.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out36 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error36 ./shells/oka2/multitask/36.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out36 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error36 ./shells/oka2/parego/36.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out36 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error36 ./shells/oka2/random/36.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out37 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error37 ./shells/oka2/indep/37.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out37 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error37 ./shells/oka2/correl/37.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out37 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error37 ./shells/oka2/multitask/37.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out37 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error37 ./shells/oka2/parego/37.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out37 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error37 ./shells/oka2/random/37.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out38 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error38 ./shells/oka2/indep/38.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out38 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error38 ./shells/oka2/correl/38.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out38 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error38 ./shells/oka2/multitask/38.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out38 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error38 ./shells/oka2/parego/38.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out38 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error38 ./shells/oka2/random/38.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out39 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error39 ./shells/oka2/indep/39.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out39 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error39 ./shells/oka2/correl/39.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out39 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error39 ./shells/oka2/multitask/39.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out39 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error39 ./shells/oka2/parego/39.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out39 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error39 ./shells/oka2/random/39.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out40 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error40 ./shells/oka2/indep/40.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out40 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error40 ./shells/oka2/correl/40.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out40 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error40 ./shells/oka2/multitask/40.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out40 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error40 ./shells/oka2/parego/40.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out40 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error40 ./shells/oka2/random/40.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out41 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error41 ./shells/oka2/indep/41.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out41 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error41 ./shells/oka2/correl/41.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out41 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error41 ./shells/oka2/multitask/41.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out41 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error41 ./shells/oka2/parego/41.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out41 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error41 ./shells/oka2/random/41.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out42 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error42 ./shells/oka2/indep/42.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out42 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error42 ./shells/oka2/correl/42.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out42 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error42 ./shells/oka2/multitask/42.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out42 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error42 ./shells/oka2/parego/42.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out42 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error42 ./shells/oka2/random/42.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out43 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error43 ./shells/oka2/indep/43.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out43 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error43 ./shells/oka2/correl/43.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out43 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error43 ./shells/oka2/multitask/43.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out43 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error43 ./shells/oka2/parego/43.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out43 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error43 ./shells/oka2/random/43.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out44 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error44 ./shells/oka2/indep/44.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out44 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error44 ./shells/oka2/correl/44.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out44 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error44 ./shells/oka2/multitask/44.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out44 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error44 ./shells/oka2/parego/44.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out44 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error44 ./shells/oka2/random/44.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out45 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error45 ./shells/oka2/indep/45.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out45 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error45 ./shells/oka2/correl/45.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out45 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error45 ./shells/oka2/multitask/45.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out45 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error45 ./shells/oka2/parego/45.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out45 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error45 ./shells/oka2/random/45.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out46 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error46 ./shells/oka2/indep/46.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out46 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error46 ./shells/oka2/correl/46.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out46 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error46 ./shells/oka2/multitask/46.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out46 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error46 ./shells/oka2/parego/46.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out46 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error46 ./shells/oka2/random/46.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out47 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error47 ./shells/oka2/indep/47.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out47 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error47 ./shells/oka2/correl/47.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out47 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error47 ./shells/oka2/multitask/47.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out47 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error47 ./shells/oka2/parego/47.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out47 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error47 ./shells/oka2/random/47.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out48 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error48 ./shells/oka2/indep/48.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out48 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error48 ./shells/oka2/correl/48.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out48 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error48 ./shells/oka2/multitask/48.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out48 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error48 ./shells/oka2/parego/48.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out48 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error48 ./shells/oka2/random/48.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out49 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error49 ./shells/oka2/indep/49.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out49 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error49 ./shells/oka2/correl/49.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out49 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error49 ./shells/oka2/multitask/49.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out49 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error49 ./shells/oka2/parego/49.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out49 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error49 ./shells/oka2/random/49.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/indep/out50 -e /bigscratch/as793/multi_objective_bayesopt/oka2/indep/error50 ./shells/oka2/indep/50.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/correl/out50 -e /bigscratch/as793/multi_objective_bayesopt/oka2/correl/error50 ./shells/oka2/correl/50.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/out50 -e /bigscratch/as793/multi_objective_bayesopt/oka2/multitask/error50 ./shells/oka2/multitask/50.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/parego/out50 -e /bigscratch/as793/multi_objective_bayesopt/oka2/parego/error50 ./shells/oka2/parego/50.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/oka2/random/out50 -e /bigscratch/as793/multi_objective_bayesopt/oka2/random/error50 ./shells/oka2/random/50.sh
