qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/indep/out1 -e /bigscratch/as793/multi_objective_bayesopt/rocket/indep/error1 ./shells/rocket/indep/v1.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/correl/out1 -e /bigscratch/as793/multi_objective_bayesopt/rocket/correl/error1 ./shells/rocket/correl/v1.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/multitask/out1 -e /bigscratch/as793/multi_objective_bayesopt/rocket/multitask/error1 ./shells/rocket/multitask/v1.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/indep/out2 -e /bigscratch/as793/multi_objective_bayesopt/rocket/indep/error2 ./shells/rocket/indep/v2.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/correl/out2 -e /bigscratch/as793/multi_objective_bayesopt/rocket/correl/error2 ./shells/rocket/correl/v2.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/multitask/out2 -e /bigscratch/as793/multi_objective_bayesopt/rocket/multitask/error2 ./shells/rocket/multitask/v2.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/indep/out3 -e /bigscratch/as793/multi_objective_bayesopt/rocket/indep/error3 ./shells/rocket/indep/v3.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/correl/out3 -e /bigscratch/as793/multi_objective_bayesopt/rocket/correl/error3 ./shells/rocket/correl/v3.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/multitask/out3 -e /bigscratch/as793/multi_objective_bayesopt/rocket/multitask/error3 ./shells/rocket/multitask/v3.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/indep/out4 -e /bigscratch/as793/multi_objective_bayesopt/rocket/indep/error4 ./shells/rocket/indep/v4.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/correl/out4 -e /bigscratch/as793/multi_objective_bayesopt/rocket/correl/error4 ./shells/rocket/correl/v4.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/multitask/out4 -e /bigscratch/as793/multi_objective_bayesopt/rocket/multitask/error4 ./shells/rocket/multitask/v4.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/indep/out5 -e /bigscratch/as793/multi_objective_bayesopt/rocket/indep/error5 ./shells/rocket/indep/v5.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/correl/out5 -e /bigscratch/as793/multi_objective_bayesopt/rocket/correl/error5 ./shells/rocket/correl/v5.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/multitask/out5 -e /bigscratch/as793/multi_objective_bayesopt/rocket/multitask/error5 ./shells/rocket/multitask/v5.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/indep/out6 -e /bigscratch/as793/multi_objective_bayesopt/rocket/indep/error6 ./shells/rocket/indep/v6.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/correl/out6 -e /bigscratch/as793/multi_objective_bayesopt/rocket/correl/error6 ./shells/rocket/correl/v6.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/multitask/out6 -e /bigscratch/as793/multi_objective_bayesopt/rocket/multitask/error6 ./shells/rocket/multitask/v6.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/indep/out7 -e /bigscratch/as793/multi_objective_bayesopt/rocket/indep/error7 ./shells/rocket/indep/v7.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/correl/out7 -e /bigscratch/as793/multi_objective_bayesopt/rocket/correl/error7 ./shells/rocket/correl/v7.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/multitask/out7 -e /bigscratch/as793/multi_objective_bayesopt/rocket/multitask/error7 ./shells/rocket/multitask/v7.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/indep/out8 -e /bigscratch/as793/multi_objective_bayesopt/rocket/indep/error8 ./shells/rocket/indep/v8.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/correl/out8 -e /bigscratch/as793/multi_objective_bayesopt/rocket/correl/error8 ./shells/rocket/correl/v8.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/multitask/out8 -e /bigscratch/as793/multi_objective_bayesopt/rocket/multitask/error8 ./shells/rocket/multitask/v8.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/indep/out9 -e /bigscratch/as793/multi_objective_bayesopt/rocket/indep/error9 ./shells/rocket/indep/v9.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/correl/out9 -e /bigscratch/as793/multi_objective_bayesopt/rocket/correl/error9 ./shells/rocket/correl/v9.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/multitask/out9 -e /bigscratch/as793/multi_objective_bayesopt/rocket/multitask/error9 ./shells/rocket/multitask/v9.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/indep/out10 -e /bigscratch/as793/multi_objective_bayesopt/rocket/indep/error10 ./shells/rocket/indep/v10.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/correl/out10 -e /bigscratch/as793/multi_objective_bayesopt/rocket/correl/error10 ./shells/rocket/correl/v10.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/multitask/out10 -e /bigscratch/as793/multi_objective_bayesopt/rocket/multitask/error10 ./shells/rocket/multitask/v10.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/indep/out11 -e /bigscratch/as793/multi_objective_bayesopt/rocket/indep/error11 ./shells/rocket/indep/v11.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/correl/out11 -e /bigscratch/as793/multi_objective_bayesopt/rocket/correl/error11 ./shells/rocket/correl/v11.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/multitask/out11 -e /bigscratch/as793/multi_objective_bayesopt/rocket/multitask/error11 ./shells/rocket/multitask/v11.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/indep/out12 -e /bigscratch/as793/multi_objective_bayesopt/rocket/indep/error12 ./shells/rocket/indep/v12.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/correl/out12 -e /bigscratch/as793/multi_objective_bayesopt/rocket/correl/error12 ./shells/rocket/correl/v12.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/multitask/out12 -e /bigscratch/as793/multi_objective_bayesopt/rocket/multitask/error12 ./shells/rocket/multitask/v12.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/indep/out13 -e /bigscratch/as793/multi_objective_bayesopt/rocket/indep/error13 ./shells/rocket/indep/v13.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/correl/out13 -e /bigscratch/as793/multi_objective_bayesopt/rocket/correl/error13 ./shells/rocket/correl/v13.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/multitask/out13 -e /bigscratch/as793/multi_objective_bayesopt/rocket/multitask/error13 ./shells/rocket/multitask/v13.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/indep/out14 -e /bigscratch/as793/multi_objective_bayesopt/rocket/indep/error14 ./shells/rocket/indep/v14.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/correl/out14 -e /bigscratch/as793/multi_objective_bayesopt/rocket/correl/error14 ./shells/rocket/correl/v14.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/multitask/out14 -e /bigscratch/as793/multi_objective_bayesopt/rocket/multitask/error14 ./shells/rocket/multitask/v14.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/indep/out15 -e /bigscratch/as793/multi_objective_bayesopt/rocket/indep/error15 ./shells/rocket/indep/v15.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/correl/out15 -e /bigscratch/as793/multi_objective_bayesopt/rocket/correl/error15 ./shells/rocket/correl/v15.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/multitask/out15 -e /bigscratch/as793/multi_objective_bayesopt/rocket/multitask/error15 ./shells/rocket/multitask/v15.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/indep/out16 -e /bigscratch/as793/multi_objective_bayesopt/rocket/indep/error16 ./shells/rocket/indep/v16.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/correl/out16 -e /bigscratch/as793/multi_objective_bayesopt/rocket/correl/error16 ./shells/rocket/correl/v16.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/multitask/out16 -e /bigscratch/as793/multi_objective_bayesopt/rocket/multitask/error16 ./shells/rocket/multitask/v16.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/indep/out17 -e /bigscratch/as793/multi_objective_bayesopt/rocket/indep/error17 ./shells/rocket/indep/v17.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/correl/out17 -e /bigscratch/as793/multi_objective_bayesopt/rocket/correl/error17 ./shells/rocket/correl/v17.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/multitask/out17 -e /bigscratch/as793/multi_objective_bayesopt/rocket/multitask/error17 ./shells/rocket/multitask/v17.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/indep/out18 -e /bigscratch/as793/multi_objective_bayesopt/rocket/indep/error18 ./shells/rocket/indep/v18.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/correl/out18 -e /bigscratch/as793/multi_objective_bayesopt/rocket/correl/error18 ./shells/rocket/correl/v18.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/multitask/out18 -e /bigscratch/as793/multi_objective_bayesopt/rocket/multitask/error18 ./shells/rocket/multitask/v18.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/indep/out19 -e /bigscratch/as793/multi_objective_bayesopt/rocket/indep/error19 ./shells/rocket/indep/v19.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/correl/out19 -e /bigscratch/as793/multi_objective_bayesopt/rocket/correl/error19 ./shells/rocket/correl/v19.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/multitask/out19 -e /bigscratch/as793/multi_objective_bayesopt/rocket/multitask/error19 ./shells/rocket/multitask/v19.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/indep/out20 -e /bigscratch/as793/multi_objective_bayesopt/rocket/indep/error20 ./shells/rocket/indep/v20.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/correl/out20 -e /bigscratch/as793/multi_objective_bayesopt/rocket/correl/error20 ./shells/rocket/correl/v20.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/multitask/out20 -e /bigscratch/as793/multi_objective_bayesopt/rocket/multitask/error20 ./shells/rocket/multitask/v20.sh
