qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out1 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error1 ./shells/rocket/random/v1.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out1 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error1 ./shells/rocket/parego/v1.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out2 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error2 ./shells/rocket/random/v2.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out2 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error2 ./shells/rocket/parego/v2.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out3 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error3 ./shells/rocket/random/v3.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out3 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error3 ./shells/rocket/parego/v3.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out4 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error4 ./shells/rocket/random/v4.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out4 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error4 ./shells/rocket/parego/v4.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out5 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error5 ./shells/rocket/random/v5.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out5 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error5 ./shells/rocket/parego/v5.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out6 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error6 ./shells/rocket/random/v6.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out6 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error6 ./shells/rocket/parego/v6.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out7 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error7 ./shells/rocket/random/v7.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out7 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error7 ./shells/rocket/parego/v7.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out8 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error8 ./shells/rocket/random/v8.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out8 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error8 ./shells/rocket/parego/v8.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out9 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error9 ./shells/rocket/random/v9.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out9 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error9 ./shells/rocket/parego/v9.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out10 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error10 ./shells/rocket/random/v10.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out10 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error10 ./shells/rocket/parego/v10.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out11 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error11 ./shells/rocket/random/v11.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out11 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error11 ./shells/rocket/parego/v11.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out12 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error12 ./shells/rocket/random/v12.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out12 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error12 ./shells/rocket/parego/v12.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out13 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error13 ./shells/rocket/random/v13.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out13 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error13 ./shells/rocket/parego/v13.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out14 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error14 ./shells/rocket/random/v14.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out14 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error14 ./shells/rocket/parego/v14.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out15 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error15 ./shells/rocket/random/v15.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out15 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error15 ./shells/rocket/parego/v15.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out16 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error16 ./shells/rocket/random/v16.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out16 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error16 ./shells/rocket/parego/v16.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out17 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error17 ./shells/rocket/random/v17.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out17 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error17 ./shells/rocket/parego/v17.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out18 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error18 ./shells/rocket/random/v18.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out18 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error18 ./shells/rocket/parego/v18.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out19 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error19 ./shells/rocket/random/v19.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out19 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error19 ./shells/rocket/parego/v19.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out20 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error20 ./shells/rocket/random/v20.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out20 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error20 ./shells/rocket/parego/v20.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out21 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error21 ./shells/rocket/random/v21.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out21 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error21 ./shells/rocket/parego/v21.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out22 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error22 ./shells/rocket/random/v22.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out22 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error22 ./shells/rocket/parego/v22.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out23 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error23 ./shells/rocket/random/v23.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out23 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error23 ./shells/rocket/parego/v23.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out24 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error24 ./shells/rocket/random/v24.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out24 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error24 ./shells/rocket/parego/v24.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out25 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error25 ./shells/rocket/random/v25.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out25 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error25 ./shells/rocket/parego/v25.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out26 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error26 ./shells/rocket/random/v26.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out26 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error26 ./shells/rocket/parego/v26.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out27 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error27 ./shells/rocket/random/v27.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out27 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error27 ./shells/rocket/parego/v27.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out28 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error28 ./shells/rocket/random/v28.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out28 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error28 ./shells/rocket/parego/v28.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out29 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error29 ./shells/rocket/random/v29.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out29 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error29 ./shells/rocket/parego/v29.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out30 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error30 ./shells/rocket/random/v30.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out30 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error30 ./shells/rocket/parego/v30.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out31 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error31 ./shells/rocket/random/v31.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out31 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error31 ./shells/rocket/parego/v31.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out32 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error32 ./shells/rocket/random/v32.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out32 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error32 ./shells/rocket/parego/v32.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out33 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error33 ./shells/rocket/random/v33.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out33 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error33 ./shells/rocket/parego/v33.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out34 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error34 ./shells/rocket/random/v34.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out34 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error34 ./shells/rocket/parego/v34.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out35 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error35 ./shells/rocket/random/v35.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out35 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error35 ./shells/rocket/parego/v35.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out36 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error36 ./shells/rocket/random/v36.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out36 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error36 ./shells/rocket/parego/v36.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out37 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error37 ./shells/rocket/random/v37.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out37 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error37 ./shells/rocket/parego/v37.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out38 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error38 ./shells/rocket/random/v38.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out38 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error38 ./shells/rocket/parego/v38.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out39 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error39 ./shells/rocket/random/v39.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out39 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error39 ./shells/rocket/parego/v39.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out40 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error40 ./shells/rocket/random/v40.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out40 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error40 ./shells/rocket/parego/v40.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out41 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error41 ./shells/rocket/random/v41.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out41 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error41 ./shells/rocket/parego/v41.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out42 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error42 ./shells/rocket/random/v42.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out42 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error42 ./shells/rocket/parego/v42.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out43 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error43 ./shells/rocket/random/v43.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out43 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error43 ./shells/rocket/parego/v43.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out44 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error44 ./shells/rocket/random/v44.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out44 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error44 ./shells/rocket/parego/v44.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out45 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error45 ./shells/rocket/random/v45.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out45 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error45 ./shells/rocket/parego/v45.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out46 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error46 ./shells/rocket/random/v46.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out46 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error46 ./shells/rocket/parego/v46.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out47 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error47 ./shells/rocket/random/v47.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out47 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error47 ./shells/rocket/parego/v47.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out48 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error48 ./shells/rocket/random/v48.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out48 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error48 ./shells/rocket/parego/v48.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out49 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error49 ./shells/rocket/random/v49.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out49 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error49 ./shells/rocket/parego/v49.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/random/out50 -e /bigscratch/as793/multi_objective_bayesopt/rocket/random/error50 ./shells/rocket/random/v50.sh
qsub -o /bigscratch/as793/multi_objective_bayesopt/rocket/parego/out50 -e /bigscratch/as793/multi_objective_bayesopt/rocket/parego/error50 ./shells/rocket/parego/v50.sh
